### ISSUE TITLE
Optimize the chatbot.

### ISSUE THREAD

**Issue by silkie261001** [ContriHUB/PlayTopia#6]
There is a chatbot on this website that suggests the song name and gives Spotify a link. Try Integrating the Spotify API into a chatbot to suggest songs and allow users to play them directly within the chat interface.

**Comment by lokesh-wagh** [comment]
Hey!!

I would like to work on this issue

**Comment by silkie261001** [comment]
Ok do it

**Comment by lokesh-wagh** [comment]
Can you provide me with the credential's to the diagflow bot

so that I can work on it

**Comment by lokesh-wagh** [comment]
If it's possible 
you can give me a clone of the diagflow chat bot to work with !

**Comment by silkie261001** [comment]
drop your email id

**Comment by lokesh-wagh** [comment]
lokeshwagh200404@gmail.com

you can also use lokesh.20223137@mnnit.ac.in

**Comment by lokesh-wagh** [comment]
![image](https://github.com/ContriHUB/PlayTopia/assets/129964049/5ff4f9ec-edd7-4b77-9596-20cd197b3e0a)

Mam,
I am getting this error using the key provided by you

when i use my own key (for my diagflow chatbot) it works fine

here's the concerned code 
![image](https://github.com/ContriHUB/PlayTopia/assets/129964049/eae9f2c9-a1f0-4f0b-b056-b4e9a2eab7f7)

can you help me with this

**Comment by silkie261001** [comment]
Try your own if it's working

**Comment by lokesh-wagh** [comment]
But my chatbot cannot suggest song's using the spotify link

i need that functionallity

**Comment by silkie261001** [comment]
have you used api

**Comment by lokesh-wagh** [comment]
Ok

I will try that

**Comment by lokesh-wagh** [comment]
Hey!!

I am planning to use spotify api to get the song's through their uri's
then play it in the frontend using spotify web playback sdk

however, spotify web playback require's spotify premium to play songs
![image](https://github.com/ContriHUB/PlayTopia/assets/129964049/bd7c89d2-0e92-451a-927c-3acffd0deeb2)
linktodocs : https://developer.spotify.com/documentation/web-playback-sdk/howtos/web-app-player

so that would mean any account that is going to be used as a medium to setup spotify play functionallity would require their premium

Is that fine with you??

bcoz this is the only way that i have figured out so far!!

**Comment by lokesh-wagh** [comment]
Also can you regenerate the credential key that you have sent me 
Maybe the key is old and that is causing that error

using the correct bot would speed up the process


Thank you for help and I apologize for any inconvenience

**Comment by silkie261001** [comment]
you can regenerate on your own
if spotify is not working you can rebuild that bot on our own in the way
you like. If i like it i will also give you bonus points

**Comment by lokesh-wagh** [comment]
Hey @silkie261001 can you review the pr

**Comment by silkie261001** [comment]
i will do till evening
